import type { IndustryConfig, IndustryId } from '@/types/scenario';

export const INDUSTRIES: Record<IndustryId, IndustryConfig> = {
  aerospace: {
    id: 'aerospace',
    label: 'Aerospace',
    iconName: 'Plane',
    primaryColor: '#1E40AF',
    accentColor: '#3B82F6',
    roles: [
      {
        id: 'inzynier-automatyki',
        label: 'Inżynier Automatyki',
        description: 'Pracuje przy systemach FADEC, awionice, kontroli lotu',
        emotionalProfile: 'reaguje na techniczne deadliny i autorytet regulacyjny EASA',
      },
      {
        id: 'technik-utrzymania',
        label: 'Technik Utrzymania Ruchu',
        description: 'Odpowiada za przeglądy i naprawy systemów pokładowych',
        emotionalProfile: 'reaguje na alarmy o krytycznym statusie sprzętu',
      },
      {
        id: 'inzynier-jakosci',
        label: 'Inżynier Jakości',
        description: 'Walidacja zgodności z normami DO-178C, DO-254',
        emotionalProfile: 'reaguje na wymagania audytowe i compliance',
      },
    ],
    vocabulary: [
      'certyfikat EASA Part-145',
      'system FADEC',
      'sterownik FBW',
      'audyt avioniki',
      'weryfikacja firmware',
      'deadline regulacyjny',
      'inspekcja techniczna',
      'norma DO-178C',
      'norma DO-254',
      'AOG (Aircraft On Ground)',
      'sterownik silnika',
      'system kontroli lotu',
      'flight management system',
      'autoryzacja lotnicza',
      'biuletyn techniczny',
    ],
    polishEmployers: [
      'PZL Mielec (Sikorsky/Lockheed Martin)',
      'WSK PZL Rzeszów (Pratt & Whitney)',
      'PZL Świdnik (Leonardo)',
      'Pratt & Whitney Rzeszów',
      'Airbus Poland (centrum R&D Warszawa)',
      'Lufthansa Technik Polska',
    ],
    fictionalSenders: [
      { name: 'Siemens Industrial Cybersecurity Center', domain: 'siemens-aerospace-cert.eu' },
      { name: 'Honeywell Aerospace Services', domain: 'honeywell-services.eu' },
      { name: 'Collins Aerospace Authentication', domain: 'collins-aero-auth.com' },
    ],
    commonScenarios: [
      'Wygaśnięcie certyfikatu systemu sterowania',
      'Krytyczna aktualizacja firmware sterownika',
      'Weryfikacja dostępu do systemu awioniki',
    ],
  },

  pharma: {
    id: 'pharma',
    label: 'Pharma',
    iconName: 'FlaskConical',
    primaryColor: '#15803D',
    accentColor: '#22C55E',
    roles: [
      {
        id: 'naukowiec-rd',
        label: 'Naukowiec R&D',
        description: 'Prowadzi badania nad nowymi substancjami w środowisku LIMS',
        emotionalProfile: 'reaguje na compliance audyt i wymagania regulacyjne',
      },
      {
        id: 'operator-produkcji',
        label: 'Operator Produkcji',
        description: 'Obsługuje linie produkcyjne zgodnie z GMP',
        emotionalProfile: 'reaguje na alerty o statusie batchu',
      },
      {
        id: 'specjalista-qa',
        label: 'Specjalista QA',
        description: 'Walidacja procesów CSV i kontrola jakości',
        emotionalProfile: 'reaguje na wymagania FDA i audytów',
      },
    ],
    vocabulary: [
      'system LIMS',
      'GMP (Good Manufacturing Practice)',
      'walidacja CSV',
      'batch record',
      'deviation report',
      'audyt FDA',
      'certyfikat GMP',
      'CAPA (Corrective Action Preventive Action)',
      'czystość mikrobiologiczna',
      'kontrola laboratoryjna',
      'master batch record',
      'change control',
      'kwalifikacja IQ/OQ/PQ',
      'audyt jakości',
      'release na rynek',
    ],
    polishEmployers: [
      'Polpharma (Starogard Gdański)',
      'Adamed Pharma (Pieńków)',
      'Mabion (Konstantynów Łódzki)',
      'Celon Pharma (Kijewo)',
      'Bayer Polska',
      'Sanofi Polska',
    ],
    fictionalSenders: [
      { name: 'Veeva Systems Vault Support', domain: 'veeva-vault-support.eu' },
      { name: 'Thermo Fisher Scientific Auth', domain: 'thermofisher-auth.com' },
      { name: 'ABB Pharma Process Control', domain: 'abb-pharma-eu.com' },
    ],
    commonScenarios: [
      'Aktualizacja systemu LIMS — wymagana akcja',
      'Reset hasła do bazy substancji kontrolowanych',
      'Weryfikacja certyfikatu GMP przed audytem',
    ],
  },

  energy: {
    id: 'energy',
    label: 'Energy',
    iconName: 'Zap',
    primaryColor: '#A16207',
    accentColor: '#EAB308',
    roles: [
      {
        id: 'operator-sterowni',
        label: 'Operator Sterowni',
        description: 'Monitoruje SCADA HMI i steruje systemem dystrybucji',
        emotionalProfile: 'reaguje na alarmy systemowe SCADA',
      },
      {
        id: 'inzynier-utrzymania',
        label: 'Inżynier Utrzymania',
        description: 'Odpowiada za PLC, RTU, integrację IEC 61850',
        emotionalProfile: 'reaguje na techniczne deadliny aktualizacji firmware',
      },
      {
        id: 'specjalista-ot-security',
        label: 'Specjalista OT Security',
        description: 'Zarządza bezpieczeństwem sieci OT i ICS',
        emotionalProfile: 'reaguje na alerty bezpieczeństwa i compliance NIS2',
      },
    ],
    vocabulary: [
      'system SCADA HMI',
      'sterownik PLC',
      'RTU (Remote Terminal Unit)',
      'protokół IEC 61850',
      'dyspozytornia OSD',
      'aktualizacja firmware',
      'sieć OT',
      'system ICS',
      'krzywa obciążenia',
      'sekcja rozdzielcza',
      'system DCS',
      'modbus TCP',
      'profibus',
      'redundancja N+1',
      'bilans mocy',
    ],
    polishEmployers: [
      'PGE Polska Grupa Energetyczna',
      'Tauron Dystrybucja',
      'Enea Operator',
      'Energa-Operator (Orlen)',
      'PSE (Polskie Sieci Elektroenergetyczne)',
      'PGNIG Termika (Orlen)',
    ],
    fictionalSenders: [
      { name: 'Siemens Energy Grid Cybersecurity', domain: 'siemens-energy-cert.eu' },
      { name: 'Schneider Electric Industrial', domain: 'schneider-industrial.eu' },
      { name: 'ABB Power Systems Security', domain: 'abb-power-sec.com' },
    ],
    commonScenarios: [
      'Krytyczna aktualizacja firmware PLC — alert SCADA',
      'Alert systemu SCADA — wymagana weryfikacja dostępu',
      'Weryfikacja dostępu do sterowni przed audytem NIS2',
    ],
  },

  manufacturing: {
    id: 'manufacturing',
    label: 'Manufacturing',
    iconName: 'Factory',
    primaryColor: '#C2410C',
    accentColor: '#F97316',
    roles: [
      {
        id: 'operator-cnc',
        label: 'Operator Maszyn CNC',
        description: 'Obsługuje centra obróbcze CNC i programy G-code',
        emotionalProfile: 'reaguje na alarmy maszynowe i andon',
      },
      {
        id: 'inzynier-procesu',
        label: 'Inżynier Procesu',
        description: 'Optymalizuje OEE i integrację MES z linią produkcyjną',
        emotionalProfile: 'reaguje na techniczne wymagania Industry 4.0',
      },
      {
        id: 'kierownik-utrzymania',
        label: 'Kierownik Utrzymania Ruchu',
        description: 'Zarządza utrzymaniem prewencyjnym i predykcyjnym',
        emotionalProfile: 'reaguje na alerty o ryzyku przestoju',
      },
    ],
    vocabulary: [
      'system MES',
      'OEE (Overall Equipment Effectiveness)',
      'CNC G-code',
      'andon system',
      'Industry 4.0',
      'utrzymanie predykcyjne',
      'kontrola jakości SPC',
      'TPM (Total Productive Maintenance)',
      'system ERP-MES',
      'paszport maszyny',
      'kalibracja narzędzi',
      'certyfikat ISO 9001',
      'lean manufacturing',
      'kanban elektroniczny',
      'cykl produkcyjny',
    ],
    polishEmployers: [
      'KGHM Polska Miedź',
      'Volkswagen Poznań',
      'Stellantis (Fiat) Tychy',
      'Toyota Manufacturing Poland (Jelcz-Laskowice)',
      'Solaris Bus & Coach (Bolechowo)',
      'Mercedes-Benz Manufacturing Poland (Jawor)',
    ],
    fictionalSenders: [
      { name: 'Siemens MES Support Center', domain: 'siemens-mes-eu.com' },
      { name: 'Rockwell Automation Auth', domain: 'rockwell-auth.com' },
      { name: 'ABB Robotics Service', domain: 'abb-robotics-eu.com' },
    ],
    commonScenarios: [
      'Aktualizacja oprogramowania maszyny CNC — wymagana akcja',
      'Wygaśnięcie certyfikatu systemu MES',
      'Reset dostępu do linii produkcyjnej przed inspekcją',
    ],
  },

  fintech: {
    id: 'fintech',
    label: 'Fintech',
    iconName: 'Landmark',
    primaryColor: '#1E3A8A',
    accentColor: '#6366F1',
    roles: [
      {
        id: 'developer-backend',
        label: 'Developer Backend',
        description: 'Implementuje integracje SWIFT, FIX, systemy tradingowe',
        emotionalProfile: 'reaguje na techniczne deadliny i wymogi regulacyjne KNF',
      },
      {
        id: 'analityk-ryzyka',
        label: 'Analityk Ryzyka',
        description: 'Odpowiada za KYC, AML i raportowanie compliance',
        emotionalProfile: 'reaguje na audyty i wymagania regulatorów',
      },
      {
        id: 'specjalista-security',
        label: 'Specjalista Security',
        description: 'Zarządza certyfikatami SSL, tokenami API, dostępami',
        emotionalProfile: 'reaguje na alerty o naruszeniach bezpieczeństwa',
      },
    ],
    vocabulary: [
      'SWIFT MT103',
      'KYC / AML',
      'protokół FIX',
      'settlement T+2',
      'token API',
      'certyfikat SSL/TLS',
      'system tradingowy',
      'regulacje KNF',
      'PSD2',
      'GDPR / RODO',
      'platforma rozliczeniowa',
      'kanał ESB',
      'system core banking',
      'PCI DSS',
      'order management system',
    ],
    polishEmployers: [
      'PKO Bank Polski',
      'mBank',
      'ING Bank Śląski',
      'XTB (Dom Maklerski X-Trade Brokers)',
      'Conotoxia / Cinkciarz.pl',
      'Santander Bank Polska',
    ],
    fictionalSenders: [
      { name: 'Bloomberg Terminal Support', domain: 'bloomberg-terminal.eu' },
      { name: 'Refinitiv (LSEG) Authentication', domain: 'refinitiv-auth.com' },
      { name: 'SWIFT Network Operations', domain: 'swift-ops-eu.com' },
    ],
    commonScenarios: [
      'Wygaśnięcie tokenu API — natychmiastowa akcja',
      'Aktualizacja certyfikatu SSL systemu tradingowego',
      'Weryfikacja dostępu do platformy rozliczeniowej',
    ],
  },
};

export const INDUSTRY_LIST: IndustryConfig[] = Object.values(INDUSTRIES);

export function getIndustry(id: IndustryId): IndustryConfig {
  return INDUSTRIES[id];
}

export function getRole(industryId: IndustryId, roleId: string) {
  const industry = INDUSTRIES[industryId];
  return industry.roles.find((r) => r.id === roleId);
}
